name: publish
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run? (y/N)"
        required: true
        default: "N"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache

      - name: New version (dry run)
        if: |
          github.ref == 'refs/heads/main'
          && contains(github.event.inputs.dry-run, 'y')
        run: yarn lerna version --yes --no-push --exact --conventional-commits --conventional-graduate --changelog-preset conventional-changelog-conventionalcommits --no-git-tag-version --loglevel=verbose

      - name: Configure Git user
        if: |
          github.ref == 'refs/heads/main'
          && contains(github.event.inputs.dry-run, 'y') == false
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: New version
        if: |
          github.ref == 'refs/heads/main'
          && contains(github.event.inputs.dry-run, 'y') == false
        run: |
          yarn lerna version --yes --push --exact --conventional-commits --conventional-graduate --changelog-preset conventional-changelog-conventionalcommits --create-release=github -m 'chore: release [skip ci]'
        env:
          HUSKY: 0
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - uses: actions/setup-node@v3
        if: |
          github.ref == 'refs/heads/main'
          && contains(github.event.inputs.dry-run, 'y') == false
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - run: lerna publish from-git --no-verify-access --yes
        if: |
          github.ref == 'refs/heads/main'
          && contains(github.event.inputs.dry-run, 'y') == false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
