name: Commit changes on @pob/root update

on:
  push:
    branches:
      - 'renovate/typedoc-**'

jobs:
  run-install-and-commit-modified-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
          key: v2-dependencies--${{ matrix.node-version }}-${{ runner.OS }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v2-dependencies--${{ matrix.node-version }}-${{ runner.OS }}-
            v2-dependencies--${{ matrix.node-version }}-

      - name: Check Dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run generate:docs
        run: yarn run generate:docs

      - name: Check for added or modified files
        id: git-check-modified
        run: echo ::set-output name=modified::$(if [[ -z $(git status -s) ]]; then echo "false"; else echo "true"; fi)

      - name: Commit report
        if: steps.git-check-modified.outputs.modified == 'true'
        run: |
          git add .
          git -c user.name="Christophe Hurpeau" \
            -c user.email="christophehurpeau@users.noreply.github.com" \
            commit -m "chore: update pob root" --author="github-actions[bot] <actions@github.com>"
          git push
