name: Release
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        required: true
        type: boolean
        default: false
      allow-no-tags:
        description: "Allow no tags"
        required: false
        type: boolean
        default: false

permissions:
  id-token: write # Required for OIDC
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.PUSH_DEPLOY_KEY }}
          fetch-depth: 0
          fetch-tags: true

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          check-latest: true
          registry-url: "https://registry.npmjs.org"

      - name: Check git tags
        if: github.ref == 'refs/heads/main' && !inputs.allow-no-tags
        run: |
          tags=$(git tag)
          if [ -z "$tags" ]; then
            echo "No git tags found"
            exit 1
          fi

      - name: Install Dependencies
        run: yarn install --immutable

      - name: New version (dry run)
        if: github.ref == 'refs/heads/main' && inputs.dry-run
        run: yarn run pob-version --dry-run

      - name: Configure Git user
        if: github.ref == 'refs/heads/main' && !inputs.dry-run
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: New version
        if: github.ref == 'refs/heads/main' && !inputs.dry-run
        run: |
          yarn run pob-version --create-release=github  -m 'chore: release %v [skip ci]'
        env:
          POB_GIT_HOOKS: 0
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        if: github.ref == 'refs/heads/main' && !inputs.dry-run
        run: |
          if [ -z "$NPM_AUTH_TOKEN" ]; then
            echo "Missing env variable NPM_AUTH_TOKEN"
            exit 1
          fi
          echo >> ./.yarnrc.yml
          echo "npmAuthToken: $NPM_AUTH_TOKEN" >> ./.yarnrc.yml
          yarn workspaces foreach --all --parallel --no-private npm publish --tolerate-republish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
